export default {
  title: "东师介绍",
  grey: true,
  hidden: true,
  content: [
    {
      tag: "grid",
      header: "学院介绍",
      content: [
        {
          text: "学校概况",
          color: "red",
          name: "Description",
          icon: "/icon/about.svg",
          path: "about/index",
        },
        {
          text: "招生概况",
          color: "orange",
          name: "Enroll",
          icon: "/icon/about.svg",
          path: "enroll/index",
        },
      ],
    },
    {
      tag: "grid",
      header: "学院介绍",
      content: [
        {
          text: "教育学部",
          color: "blue",
          name: "Education",
          icon: "/icon/intro/education.svg",
          path: "school/education/index",
        },
        {
          text: "心理学院",
          color: "orange",
          name: "Psychology",
          icon: "/icon/intro/psychology.svg",
          path: "school/psychology/index",
        },
        {
          text: "政法学院",
          color: "red",
          name: "Politics",
          icon: "/icon/intro/politics.svg",
          path: "school/politics/index",
        },
        {
          text: "经济与管理学院",
          color: "purple",
          name: "Economy",
          icon: "/icon/intro/economy.svg",
          path: "school/economy/index",
        },
        {
          text: "文学院",
          color: "cyan",
          name: "Chinese",
          icon: "/icon/intro/chinese.svg",
          path: "school/chinese/index",
        },
        {
          text: "历史文化学院",
          color: "olive",
          name: "History",
          icon: "/icon/intro/history.svg",
          path: "school/history/index",
        },
        {
          text: "外国语学院",
          color: "mauve",
          name: "Foreign",
          icon: "/icon/intro/foreign.svg",
          path: "school/foreign/index",
        },
        {
          text: "音乐学院",
          color: "blue",
          name: "Music",
          icon: "/icon/intro/music.svg",
          path: "school/music/index",
        },
        {
          text: "美术学院",
          color: "orange",
          name: "Art",
          icon: "/icon/intro/art.svg",
          path: "school/art/index",
        },
        {
          text: "马克思主义学部",
          color: "red",
          name: "Marx",
          icon: "/icon/intro/marx.svg",
          path: "school/marx/index",
        },
        {
          text: "数学与统计学院",
          color: "purple",
          name: "Math",
          icon: "/icon/intro/math.svg",
          path: "school/math/index",
        },
        {
          text: "信息科学与技术学院",
          color: "cyan",
          name: "Politic",
          icon: "/icon/intro/ist.svg",
          path: "school/ist/index",
        },
        {
          text: "物理学院",
          color: "olive",
          name: "Physics",
          icon: "/icon/intro/physics.svg",
          path: "school/physics/index",
        },
        {
          text: "化学学院",
          color: "mauve",
          name: "Chemistry",
          icon: "/icon/intro/chemistry.svg",
          path: "school/chemistry/index",
        },
        {
          text: "生命科学学院",
          color: "blue",
          name: "Biology",
          icon: "/icon/intro/biology.svg",
          path: "school/biology/index",
        },
        {
          text: "地理科学学院",
          color: "orange",
          name: "Geology",
          icon: "/icon/intro/geography.svg",
          path: "school/geography/index",
        },
        {
          text: "环境学院",
          color: "red",
          name: "Env",
          icon: "/icon/intro/environment.svg",
          path: "school/environment/index",
        },
        {
          text: "体育学院",
          color: "purple",
          name: "Math",
          icon: "/icon/intro/pe.svg",
          path: "school/pe/index",
        },
        {
          text: "传媒科学学院",
          color: "cyan",
          name: "Media",
          icon: "/icon/intro/media.svg",
          path: "school/media/index",
        },
        {
          text: "国际汉学院",
          color: "olive",
          name: "Internation",
          icon: "/icon/guide/school.svg",
          path: "school/physics/index",
        },
        {
          text: "纽瓦克学院",
          color: "mauve",
          name: "Newark",
          icon: "/icon/guide/school.svg",
          path: "school/newark/index",
        },
      ],
    },
    {
      tag: "grid",
      header: "机构介绍",
      content: [
        {
          text: "党委学生工作部",
          color: "blue",
          name: "Student",
          icon: "/icon/intro/student.svg",
          path: "apartment/student",
        },
        {
          text: "学生心理健康教育中心",
          color: "orange",
          name: "Psychology",
          icon: "/icon/intro/psychology.svg",
          path: "apartment/psychology",
        },
        {
          text: "学校办公室",
          color: "red",
          name: "Office",
          icon: "/icon/intro/office.svg",
          path: "apartment/office",
        },
        {
          text: "校团委",
          color: "purple",
          name: "League",
          icon: "/icon/intro/league.svg",
          path: "apartment/youth-league",
        },
        {
          text: "后勤管理处",
          color: "cyan",
          name: "Logistics",
          icon: "/icon/intro/wrench.svg",
          path: "apartment/logistics",
        },
        {
          text: "校医院",
          color: "olive",
          name: "Hospital",
          icon: "/icon/intro/hospital.svg",
          path: "apartment/hospital/index",
        },
        {
          text: "保卫科",
          color: "mauve",
          name: "Defend",
          icon: "/icon/intro/shield.svg",
          path: "apartment/defend",
        },
        {
          text: "图书馆",
          color: "cyan",
          name: "Library",
          icon: "/icon/guide/library.svg",
          path: "apartment/library/index",
        },
      ],
      footer: " ",
    },
  ],
};
