export default {
  title: "东师指南",
  grey: true,
  hidden: true,
  content: [
    {
      tag: "grid",
      header: "新生你好",
      content: [
        {
          text: "入学准备",
          color: "orange",
          name: "Prepare",
          icon: "/icon/guide/prepare.svg",
          path: "prepare/index",
        },
        {
          text: "新生报到",
          color: "red",
          name: "Check",
          icon: "/icon/guide/check.svg",
          path: "check/index",
        },
        {
          text: "需带物品",
          color: "blue",
          name: "Necessity",
          icon: "/icon/guide/necessity.svg",
          path: "necessity/index",
        },
        {
          text: "常见问题",
          color: "cyan",
          name: "FAQ",
          icon: "/icon/guide/faq.svg",
          path: "faq/index",
        },
      ],
    },
    {
      tag: "grid",
      header: "学在东师",
      content: [
        {
          text: "学位",
          color: "blue",
          name: "Course",
          icon: "/icon/guide/degree.svg",
          path: "degree/index",
        },
        {
          text: "课程",
          color: "orange",
          name: "Course",
          icon: "/icon/guide/course.svg",
          path: "course/index",
        },
        {
          text: "学习",
          color: "red",
          name: "Study",
          icon: "/icon/guide/study.svg",
          path: "study/index",
        },
        {
          text: "选课",
          color: "purple",
          name: "Select",
          icon: "/icon/guide/select.svg",
          path: "select/index",
        },
        {
          text: "图书馆",
          color: "cyan",
          name: "Library",
          icon: "/icon/guide/library.svg",
          path: "/intro/apartment/library/index",
        },
        {
          text: "考试",
          color: "olive",
          name: "Exam",
          icon: "/icon/guide/test.svg",
          path: "exam/index",
        },
        {
          text: "资助",
          color: "mauve",
          name: "Subsidize",
          icon: "/icon/guide/subsidize.svg",
          path: "subsidize/index",
        },
      ],
    },
    {
      tag: "grid",
      header: "行在东师",
      content: [
        {
          text: "寝室",
          color: "blue",
          name: "Dorm",
          icon: "/icon/guide/dorm.svg",
          path: "dorm/index",
        },
        {
          text: "食堂",
          color: "orange",
          name: "Dining",
          icon: "/icon/guide/dining.svg",
          path: "dining/index",
        },
        {
          text: "校园卡",
          color: "red",
          name: "Card",
          icon: "/icon/guide/card.svg",
          path: "card/index",
        },

        {
          text: "校园网",
          color: "purple",
          name: "Network",
          icon: "/icon/guide/network.svg",
          path: "network/index",
        },
        {
          text: "账户",
          color: "olive",
          name: "Account",
          icon: "/icon/guide/account.svg",
          path: "account/index",
        },
        {
          text: "生活",
          color: "mauve",
          name: "Life",
          icon: "/icon/guide/life.svg",
          path: "life/index",
        },
        {
          text: "SIM 卡",
          color: "blue",
          name: "SIM",
          icon: "/icon/guide/sim.svg",
          path: "sim/index",
        },
      ],
    },
    {
      tag: "grid",
      header: "乐在东师",
      content: [
        {
          text: "学生组织",
          color: "blue",
          name: "Orgnazation",
          icon: "/icon/guide/student-org.svg",
          path: "organization/index",
        },
        {
          text: "社团",
          color: "orange",
          name: "Association",
          icon: "/icon/guide/association.svg",
          path: "association/index",
        },
        {
          text: "交通",
          color: "red",
          name: "Traffic",
          icon: "/icon/guide/traffic.svg",
          path: "traffic/index",
        },
        {
          text: "吃喝玩乐",
          color: "purple",
          name: "Nearby",
          icon: "/icon/guide/nearby.svg",
          path: "life/nearby/index",
        },
      ],
      footer: " ",
    },
  ],
};
