import { PageDataWithContent } from "../../../typings";

export default {
  title: "东师介绍",
  grey: true,
  hidden: true,
  content: [
    {
      tag: "grid",
      header: "学院介绍",
      content: [
        {
          text: "学校概况",
          color: "red",
          name: "Description",
          icon: "about",
          path: "intro/about/index",
        },
        {
          text: "招生概况",
          color: "orange",
          name: "Enroll",
          icon: "enroll",
          path: "intro/enroll/index",
        },
        {
          text: "资助",
          color: "purple",
          name: "Subsidize",
          icon: "subsidize",
          path: "intro/subsidize/index",
        },
      ],
    },
    {
      tag: "grid",
      header: "学院介绍",
      content: [
        {
          text: "教育学部",
          color: "blue",
          name: "Education",
          icon: "education",
          path: "intro/school/education/index",
        },
        {
          text: "心理学院",
          color: "orange",
          name: "Psychology",
          icon: "psychology",
          path: "intro/school/psychology/index",
        },
        {
          text: "政法学院",
          color: "red",
          name: "Politics",
          icon: "politics",
          path: "intro/school/politics/index",
        },
        {
          text: "经济与管理学院",
          color: "purple",
          name: "Economy",
          icon: "economy",
          path: "intro/school/economy/index",
        },
        {
          text: "文学院",
          color: "cyan",
          name: "Chinese",
          icon: "chinese",
          path: "intro/school/chinese/index",
        },
        {
          text: "历史文化学院",
          color: "olive",
          name: "History",
          icon: "history",
          path: "intro/school/history/index",
        },
        {
          text: "外国语学院",
          color: "mauve",
          name: "Foreign",
          icon: "foreign",
          path: "intro/school/foreign/index",
        },
        {
          text: "音乐学院",
          color: "blue",
          name: "Music",
          icon: "music",
          path: "intro/school/music/index",
        },
        {
          text: "美术学院",
          color: "orange",
          name: "Art",
          icon: "art",
          path: "intro/school/art/index",
        },
        {
          text: "马克思主义学部",
          color: "red",
          name: "Marx",
          icon: "marx",
          path: "intro/school/marx/index",
        },
        {
          text: "数学与统计学院",
          color: "purple",
          name: "Math",
          icon: "math",
          path: "intro/school/math/index",
        },
        {
          text: "信息科学与技术学院",
          color: "cyan",
          name: "Politic",
          icon: "ist",
          path: "intro/school/ist/index",
        },
        {
          text: "物理学院",
          color: "olive",
          name: "Physics",
          icon: "physics",
          path: "intro/school/physics/index",
        },
        {
          text: "化学学院",
          color: "mauve",
          name: "Chemistry",
          icon: "chemistry",
          path: "intro/school/chemistry/index",
        },
        {
          text: "生命科学学院",
          color: "blue",
          name: "Biology",
          icon: "biology",
          path: "intro/school/biology/index",
        },
        {
          text: "地理科学学院",
          color: "orange",
          name: "Geography",
          icon: "geography",
          path: "intro/school/geography/index",
        },
        {
          text: "环境学院",
          color: "red",
          name: "Env",
          icon: "environment",
          path: "intro/school/environment/index",
        },
        {
          text: "体育学院",
          color: "purple",
          name: "Pe",
          icon: "basketball",
          path: "intro/school/pe/index",
        },
        {
          text: "传媒科学学院",
          color: "cyan",
          name: "Media",
          icon: "media",
          path: "intro/school/media/index",
        },
        {
          text: "民族教育学院",
          color: "olive",
          name: "People",
          icon: "people",
          path: "intro/school/people/index",
        },
        {
          text: "国际汉学院",
          color: "mauve",
          name: "Internation",
          icon: "network",
          path: "intro/school/internation/index",
        },
        {
          text: "纽瓦克学院",
          color: "blue",
          name: "Newark",
          icon: "school",
          path: "intro/school/newark/index",
        },
      ],
    },
    {
      tag: "grid",
      header: "机构介绍",
      content: [
        {
          text: "党委学生工作部",
          color: "blue",
          name: "Student",
          icon: "student",
          path: "apartment/student/index",
        },
        {
          text: "学生心理健康教育中心",
          color: "orange",
          name: "Psychology",
          icon: "psychology",
          path: "apartment/psychology",
        },
        {
          text: "学校办公室",
          color: "red",
          name: "Office",
          icon: "office",
          path: "apartment/office",
        },
        {
          text: "校团委",
          color: "purple",
          name: "League",
          icon: "league",
          path: "apartment/youth-league",
        },
        {
          text: "后勤管理处",
          color: "cyan",
          name: "Logistics",
          icon: "wrench",
          path: "apartment/logistics/index",
        },
        {
          text: "校医院",
          color: "olive",
          name: "Hospital",
          icon: "hospital",
          path: "apartment/hospital/index",
        },
        {
          text: "保卫科",
          color: "mauve",
          name: "Defend",
          icon: "safe",
          path: "apartment/defend",
        },
        {
          text: "图书馆",
          color: "cyan",
          name: "Library",
          icon: "library",
          path: "apartment/library/index",
        },
        {
          text: "教务处",
          color: "blue",
          name: "Course",
          icon: "jwc",
          path: "apartment/course/index",
        },
      ],
      footer: " ",
    },
  ],
} as PageDataWithContent;
